<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>moodsphere-biz</artifactId>
        <groupId>com.moodsphere</groupId>
        <version>3.9.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>mood-vector</artifactId>

    <description>
        情绪向量建模模块
    </description>

    <dependencies>
        <dependency>
            <groupId>com.moodsphere</groupId>
            <artifactId>moodsphere-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.moodsphere</groupId>
            <artifactId>mood-record</artifactId>
        </dependency>
        <dependency>
            <groupId>com.moodsphere</groupId>
            <artifactId>mood-ai-analyze</artifactId>
        </dependency>
    </dependencies>

</project>
