<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>moodsphere</artifactId>
        <groupId>com.moodsphere</groupId>
        <version>3.9.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>moodsphere-biz</artifactId>
    <packaging>pom</packaging>

    <description>
        biz业务聚合模块
    </description>

    <modules>
        <module>system-user</module>
        <module>record</module>
        <module>asset</module>
        <module>ai-analyze</module>
        <module>vector</module>
        <module>weather-engine</module>
        <module>report</module>
        <module>globe</module>
        <module>risk</module>
        <module>notify</module>
        <module>config</module>
        <module>stat</module>
    </modules>

</project>